version: '3.8'

services:
  minio:
    image: minio/minio
    command: "server /data --console-address \":9001\""
    env_file:
      - .env
    ports:
      - "9000:9000"
      - "9001:9001"
    networks:
      filecrab:

  filecrab:
    image: filecrab
    depends_on:
      - minio
    ports:
      - "8080:8080"
    env_file:
      - .env
    networks:
      filecrab:

  surrealdb:
    image: surrealdb/surrealdb:latest
    container_name: surrealdb
    env_file:
      - .env
    restart: unless-stopped
    command: start --user $DB_USER --pass $DB_PASSWORD --log $DB_LOG file:/data/database.db
    user: root
    ports:
      - 8000:8000
    volumes:
      - ./sdb-data:/data
    networks:
      filecrab:

networks:
  filecrab:

volumes:
  data:

