services:
  filecrab:
    image: filecrab
    depends_on:
      - minio
      - surrealdb
    env_file:
      - .env
    volumes:
      - data:/data
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.filecrab.rule=(Host(`filecrab.localhost`) && PathPrefix(`/api`))"
      - "traefik.http.routers.filecrab.priority=52"
      - "traefik.http.routers.filecrab.entrypoints=web"
      - "traefik.http.services.filecrab.loadbalancer.server.port=8080"
    networks:
      filecrab:

  minio:
    image: minio/minio:latest
    command: 'server /data --console-address ":9001"'
    env_file:
      - .env
    ports:
      - "9000:9000"
      - "9001:9001"
    networks:
      filecrab:

  surrealdb:
    image: surrealdb/surrealdb:latest
    env_file:
      - .env
    restart: unless-stopped
    command: start --user $DB_USER --pass $DB_PASSWORD --log $DB_LOG file:/data/database.db
    user: root
    ports:
      - 8000:8000
    volumes:
      - ./data/sdb:/data
    networks:
      filecrab:

  front:
    image: filecrab-front
    networks:
      filecrab:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.front.rule=(Host(`filecrab.localhost`) && PathPrefix(`/`))"
      - "traefik.http.routers.front.entrypoints=web"
      - "traefik.http.services.front.loadbalancer.server.port=8080"

  traefik:
    image: traefik
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    networks:
      filecrab:
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

networks:
  filecrab:

volumes:
  data:
