[package]
name = "filecrab-cli"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
serde_with = { workspace = true }

tokio = { workspace = true }
anyhow = { workspace = true }
clap = { version = "4.4.18", features = ["derive"] }
config = "0.13.4"
home = "0.5.9"
reqwest = { version = "0.11.23", features = ["multipart", "json"] }
arboard = { version = "3" }
