name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    env:
      CARGO_TERM_COLOR: always
    steps:
      - uses: actions/checkout@v4

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@1.85
        with:
          components: clippy

      - uses: Swatinem/rust-cache@v2

      - name: Lint
        run: cargo clippy --all-features --tests -- -Dwarnings

      - name: Test
        run: |
          cargo test
          cargo test --all-features

  format:
    name: Format
    runs-on: ubuntu-latest
    env:
      CARGO_TERM_COLOR: always
    steps:
      - uses: actions/checkout@v4

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@1.85
        with:
          components: rustfmt

      - name: Format
        run: cargo fmt --all -- --check
