name: pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  setup:
    name: Pipeline
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup
        run: |
          rustup update stable
          rustup default stable

      - name: Format
        run: cargo fmt --all -- --check

      - name: Lint
        run: cargo clippy --all-features --tests -- -Dwarnings

      - name: Test
        run: cargo test
