name: release-server

on:
  push:
    tags:
      - filecrab-server-v*

jobs:
  release-filecrab-image:
    name: Release filecrab 
    runs-on: ubuntu-latest
    env:
      CARGO_TERM_COLOR: always
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: nicolasgoutte/filecrab
          flavor: |
            latest=false

      - name: Trim prefix from tags
        id: trim_tags
        run: |
          # Extract the version from the GitHub ref
          VERSION=${GITHUB_REF#refs/tags/filecrab-server-}
          # Set the trimmed tags
          echo "VERSION=${VERSION}" >> $GITHUB_ENV

      - name: Build and push Docker images
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            nicolasgoutte/filecrab:${{ env.VERSION }}
            nicolasgoutte/filecrab:latest
          labels: ${{ steps.meta.outputs.labels }}
          build-args: BUILD_MODE=release


  release-filecrab-rocksdb-image:
    name: Release filecrab with rocksdb embedded mode 
    runs-on: ubuntu-latest
    env:
      CARGO_TERM_COLOR: always
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: nicolasgoutte/filecrab

      - name: Trim prefix from tags
        id: trim_tags
        run: |
          # Extract the version from the GitHub ref
          VERSION=${GITHUB_REF#refs/tags/filecrab-server-}
          # Set the trimmed tags
          echo "VERSION=${VERSION}" >> $GITHUB_ENV

      - name: Build and push Docker images
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            nicolasgoutte/filecrab:rocksdb-${{ env.VERSION }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            BUILD_MODE=release 
            FEATURES=rocksdb
