name: release

on:
  push:
    tags:
      - v*

jobs:
  release-cli:
    name: Release CLI
    runs-on: ubuntu-latest
    env:
      CARGO_TERM_COLOR: always
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@1.77
        with:
          components: clippy, rustfmt

      - name: Build CLI bin
        run: |
          cargo build --package filecrab-cli --release
          mv target/release/filecrab .
          tar -zcvf filecrab.tgz filecrab

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.FILECRABDEPLOYMENT }}
          file: filecrab.tgz
          asset_name: filecrab-$tag.tgz
          tag: ${{ github.ref }}
          overwrite: true
          body: ""

  release-filecrab-image:
    name: Release filecrab 
    runs-on: ubuntu-latest
    env:
      CARGO_TERM_COLOR: always
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: nicolasgoutte/filecrab
          flavor: |
            latest=false

      - name: Build and push Docker images
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: BUILD_MODE=release


  release-filecrab-rocksdb-image:
    name: Release filecrab with rocksdb embedded mode 
    runs-on: ubuntu-latest
    env:
      CARGO_TERM_COLOR: always
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: nicolasgoutte/filecrab
          flavor: |
            latest=false
            prefix=rocksdb-

      - name: Build and push Docker images
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            BUILD_MODE=release 
            FEATURES=rocksdb

