name: release-web

on:
  push:
    tags:
      - filecrab-web-v*
jobs:
  release-filecrab-web-image:
    name: Release filecrab web image
    runs-on: ubuntu-latest
    env:
      CARGO_TERM_COLOR: always
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver-opts: image=moby/buildkit:latest

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: nicolasgoutte/filecrab-web

      - name: Trim prefix from tags
        id: trim_tags
        run: |
          # Extract the version from the GitHub ref
          VERSION=${GITHUB_REF#refs/tags/filecrab-web-}
          # Set the trimmed tags
          echo "VERSION=${VERSION}" >> $GITHUB_ENV

      - name: Build and push Docker images
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile.front
          push: true
          tags: |
            nicolasgoutte/filecrab-web:${{ env.VERSION }}
            nicolasgoutte/filecrab-web:latest
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
