name: release

on:
  push:
    tags:
      - v*

jobs:
  release-cli:
    name: Release CLI
    runs-on: ubuntu-latest
    env:
      CARGO_TERM_COLOR: always
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@1.77
        with:
          components: clippy, rustfmt

      - name: Build CLI bin
        run: cargo build --package filecrab-cli --release

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.FILECRABDEPLOYMENT }}
          file: target/release/filecrab
          asset_name: filecrab
          tag: ${{ github.ref }}
          overwrite: true
          body: ""
